---
- hosts: localhost
  connection: local
  vars:
    region: "{{region}}"
    aws_network_name: "{{aws_network_name}}"
  tasks:

    - name: Get Bastion EC2 ID using instance
#      ec2_remote_facts: # deprecated so replaced it with ec2_instance_facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ aws_network_name }}-bastion"
      register: ec2_facts

#    - debug: "var=ec2_facts"

    - name: Destroy Bastion
      ec2:
        instance_ids: "{{ item.instance_id }}"   # item.id replaced with item.instance_id to support with ec2_instance_facts
        state: absent
        region: "{{ region }}"
      with_items: "{{ ec2_facts.instances }}"
