---
- hosts: localhost
  connection: local
  vars:
    region: eu-west-1
    aws_network_name: dev
    vpc_cidr: 10.4.0.0/16
    public_subnet_cidr: 10.4.0.0/24
    private_subnet_1_cidr: 10.4.1.0/24
    private_subnet_2_cidr: 10.4.2.0/24
  gather_facts: False
  tasks:
    - name: Get VPC ID
      ec2_vpc_net_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ aws_network_name }}-vpc"
      register: vpc_facts

    - name: Destroy SG MySQL
      ec2_group:
        name: "{{ aws_network_name }}-private"
        state: absent
        region: "{{ region }}"

    - name: Destroy SG Web
      ec2_group:
        name: "{{ aws_network_name }}-web"
        state: absent
        region: "{{ region }}"

    - name: Destroy SG Bastion
      ec2_group:
        name: "{{ aws_network_name }}-bastion"
        state: absent
        region: "{{ region }}"

    - name: Remove subnet route table
      ec2_vpc_route_table:
        region: "{{ region }}"
        state: absent
        tags:
          Name: "{{ aws_network_name }}-public"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Remove Public Subnet
      ec2_vpc_subnet:
        state: absent
        cidr: "{{ public_subnet_cidr }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Remove Private Subnet 1
      ec2_vpc_subnet:
        state: absent
        cidr: "{{ private_subnet_1_cidr }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Remove Private Subnet 2
      ec2_vpc_subnet:
        state: absent
        cidr: "{{ private_subnet_2_cidr }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
        state: absent
        region: "{{ region }}"

    - name: Remove VPC
      ec2_vpc_net:
        name: "{{ aws_network_name }}-vpc"
        state: absent
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
