---
- hosts: localhost
  connection: local
  vars:
    region: "{{region}}"
    aws_network_name: "{{aws_network_name}}"
  tasks:
    - name: Remove RDS Instance
      rds:
        region: "{{ region }}"
        command: delete
        instance_name: "{{ aws_network_name }}-rds"
        wait: yes
        wait_timeout: 1800
    - name: Remove RDS Subnet Group
      rds_subnet_group:
        region: "{{ region }}"
        state: absent
        name: "{{ aws_network_name }}-subnetgroup"
    - name: Build MySQL Parameters
      rds_param_group:
        region: "{{ region }}"
        state: absent
        name: "{{ aws_network_name }}-parameters"
