---
#
# Clean up of all of the infrastructure you have created in this project.
#
# Uncomment below line if you had created RDS instance. 
#- include: cleanup-rds.yml
#- include: cleanup-bastian.yml
#- include: cleanup-networks.yml

- name: Destroy all infrastructure components
  hosts: localhost
  connection: local
  roles:
   - aws-rds-delete
   - aws-bastian-delete
   - aws-network-delete

