---
# This playbook deploys the whole AWS Network, Bastion, Web, and RDS Instances.  Web Configuration is currently manual
# - Must have credentials exported for AWS IAM
# - RDS may take up to 30 minutes to deploy the instance

- name: Deploy RDS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

# Global AWS Variables
    region: eu-west-1
    aws_network_name: dev

# VPC Variables
    vpc_cidr: 10.4.0.0/16
    public_subnet_cidr: 10.4.0.0/24
    public_subnet_az: eu-west-1a
    private_subnet_1_cidr: 10.4.1.0/24
    private_subnet_1_az: eu-west-1b
    private_subnet_2_cidr: 10.4.2.0/24
    private_subnet_2_az: eu-west-1c

# Bastion Variables
    ec2_id: "ami-00035f41c82244dab"
    key_pair: "ansible-eu-west-1"

# RDS Variables
    rds_user: root
    rds_pass: r0Ot3r123
    rds_instance_type: db.t2.small
    rds_size_gb: 15
    rds_parameter_engine: mysql5.6
    rds_instance_engine: 5.6.34
    rds_parameters:
      - { param: 'binlog_format', value: 'ROW' }
      - { param: 'general_log', value: '1' }

  roles:
  - aws-network
  - aws-bastian
  - aws-rds
