---
#
#
# AWS credentials must be provided securely in ~/.boto file in following format.
#  [Credentials]
#  AWS_ACCESS_KEY_ID=A...................Z
#  AWS_SECRET_ACCESS_KEY=A..............................Z
#
#
#
#
- name: Deploy RDS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

# Global AWS Variables
    region: "{{region}}"
    aws_network_name: "{{aws_network_name}}"

# VPC Variables
    vpc_cidr: "{{vpc_cidr}}"
    public_subnet_cidr: "{{public_subnet_cidr}}"
    public_subnet_az: "{{public_subnet_az}}"
    private_subnet_1_cidr: "{{private_subnet_1_cidr}}"
    private_subnet_2_cidr: "{{private_subnet_2_cidr}}"
    private_subnet_1_az: "{{private_subnet_1_az}}"
    private_subnet_2_az: "{{private_subnet_2_az}}"

# Bastion Variables
    ec2_id: "{{ec2_id}}"
    key_pair: "{{key_pair}}"

# RDS Variables
    rds_user: "{{rds_user}}"
    rds_pass: "{{rds_pass}}"
    rds_instance_type: "{{rds_instance_type}}"
    rds_size_gb: "{{rds_size_gb}}"
    rds_parameter_engine: "{{rds_parameter_engine}}"
    rds_instance_engine: "{{rds_instance_engine}}"
    rds_parameters: "{{rds_parameters}}"


  roles:
  # This will set up PVC, Networks and other requirement specially for this project.
  - aws-network
  # This will create a bastian host.
  - aws-bastian
  # This creates RDS instance.
  # RDS instance takes up to 30 minutes to deploy, only enable when sure.
#  - aws-rds
